# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  workflow_dispatch:
  # Schedule to run the job every hour
  schedule:
    		- cron: '*/4 * * * *'
  
jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout repository
      uses: actions/checkout@v2
      
    # Step 2: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

   # Step 3: Install dependencies (if you have a requirements.txt file)
    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    # Step 3: Generate a random delay between 0 and 24 hours

      
    - name: Set up environment variables
      run: |
        echo "ACCESS=${{ secrets.ACCESS }}" >> $GITHUB_ENV
        echo "CLOUD=${{ secrets.CLOUD }}" >> $GITHUB_ENV
        echo "NAME=${{ secrets.NAME }}" >> $GITHUB_ENV
        echo "SEC=${{ secrets.SEC }}" >> $GITHUB_ENV


    # Step 4: Run your script after the random delay
    - name: Run Python script
      run: |
        python upload.py  # Replace with your Python script nam
